"use strict";
var x = 4209.3;
var xx = 1235.5;
var xxx = 1261.5;
var xxxx = 6035.6;
var xxxxx = 16274.1;
var xxxxxx = 2100.5;
var Drei = 100;
var X_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var XX_ = X_ / Drei;
var X_X = x / XX_;
var x2008 = 4965.7;
var x2018 = 4209.3;
var _X = x2008 / Drei;
var xJahr = 100 - x2018 / _X;
var xZahl = x2008 - x2018;
console.group('Europa');
console.log("Die Emission von Europa ist" + +x + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht Europa damit " + X_X + "%.");
console.log("Für Europa hat sich 2018 im Vergleich zu 2008 die Emission um" + xJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + xZahl + " kg weniger CO2.");
console.groupEnd();
var A_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var AA_ = A_ / Drei;
var A_A = xxxx / AA_;
var a2008 = 6600.4;
var a2018 = 6035.6;
var _A = a2008 / Drei;
var AJahr = 100 - a2018 / _A;
var AZahl = a2008 - a2018;
console.group('North America');
console.log("Die Emission von North America ist" + +xxxx + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht North America damit " + A_A + "%.");
console.log("Für North America hat sich 2018 im Vergleich zu 2008 die Emission um" + AJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + AZahl + " kg weniger CO2.");
console.groupEnd();
var Y_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var YY_ = Y_ / Drei;
var Y_Y = xxx / ZZ_;
var y2008 = 1132.6;
var y2018 = 1261.5;
var _Y = y2008 / Drei;
var YJahr = 100 - y2018 / _Y;
var YZahl = y2018 - y2008;
console.group('South America');
console.log("Die Emission von South America ist" + +xxx + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht South America damit " + Y_Y + "%.");
console.log("Für South America hat sich 2018 im Vergleich zu 2008 die Emission um" + YJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + YZahl + " kg mehr CO2.");
console.groupEnd();
var Z_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var ZZ_ = Z_ / Drei;
var Z_Z = xx / ZZ_;
var z2008 = 1028;
var z2018 = 1230.5;
var _Z = z2008 / Drei;
var ZJahr = 100 - z2018 / _Z;
var ZZahl = z2018 - z2008;
console.group('Africa');
console.log("Die Emission von Africa ist" + +xx + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht Africa damit " + Z_Z + "%.");
console.log("Für Africa hat sich 2018 im Vergleich zu 2008 die Emission um" + ZJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + ZZahl + " kg mehr CO2.");
console.groupEnd();
var S_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var SS_ = S_ / Drei;
var S_S = xxxxx / SS_;
var s2008 = 12954.7;
var s2018 = 16274.1;
var _S = s2008 / Drei;
var SJahr = 100 - s2018 / _S;
var SZahl = s2018 - s2008;
console.group('Asia');
console.log("Die Emission von Asia ist" + +xxxxx + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht Asia damit " + A_A + "%.");
console.log("Für Asia hat sich 2018 im Vergleich zu 2008 die Emission um" + AJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + AZahl + " kg mehr CO2.");
console.groupEnd();
var C_ = x + xx + xxx + xxxx + xxxxx + xxxxxx;
var CC_ = C_ / Drei;
var C_C = xxxxxx / CC_;
var c2008 = 1993;
var c2018 = 2100.5;
var _C = c2008 / Drei;
var CJahr = 100 - c2018 / _S;
var CZahl = c2018 - c2008;
console.group('Australia');
console.log("Die Emission von Australia ist" + +xxxxxx + "kg CO2.");
console.log("Relativ zur Gesamtemission der Welt verursacht Australia damit " + C_C + "%.");
console.log("Für Australia hat sich 2018 im Vergleich zu 2008 die Emission um" + CJahr + " %verändert.");
console.log("2018 im Vergleich zu 2008 sind das" + CZahl + " kg mehr CO2.");
console.groupEnd();
//# sourceMappingURL=script.js.map